---

- name: Install Snapd
  package:
    name: snapd
    state: present

- name: Install a load of snaps
  community.general.snap:
    name:
      - chromium
      - ngrok
      - postman
      - signal-desktop
      - telegram-desktop
      - spotify
      - joplin-desktop
      - thunderbird

- name: Install PhpStorm
  community.general.snap:
    name: phpstorm
    classic: true
