---

provision_user: 'iain'
provision_become: true

dev_user: 'iain'

docker_users:
  - '{{ dev_user }}'

ubuntu_release_override: oracular

docker_apt_release_channel: stable
docker_apt_arch: "{{ 'arm64' if ansible_architecture == 'aarch64' else 'amd64' }}"
docker_apt_repository: "deb [arch={{ docker_apt_arch }}{{' signed-by=/etc/apt/keyrings/docker.asc' if add_repository_key is not failed}}] {{ docker_repo_url }}/{{ ansible_distribution | lower }} {{ ansible_distribution_release if ubuntu_release_override is not defined else ubuntu_release_override }} {{ docker_apt_release_channel }}"
docker_apt_ignore_key_error: True
docker_apt_gpg_key: "{{ docker_repo_url }}/{{ ansible_distribution | lower }}/gpg"
docker_apt_filename: "docker"

php_version: 8.4
php_enable_webserver: false

tailscale_login_server: "{{ lookup('password', 'credentials/tailscale.login-server') }}"
tailscale_authkey: "{{ lookup('password', 'credentials/tailscale.authkey') }}"
