---

- name: Fetch powerline-go binary
  ansible.builtin.get_url:
    url: "https://github.com/justjanne/powerline-go/releases/download/v1.25/powerline-go-linux-amd64"
    dest: /usr/local/bin/powerline-go
    mode: 0755

- name: Update user's .bashrc
  ansible.builtin.blockinfile:
    path: "/home/{{ dev_user }}/.bashrc"
    append_newline: true
    prepend_newline: true
    block: |
      function _update_ps1() {
        PS1="$(powerline-go \
          -newline \
          -error $? \
          -cwd-max-depth 4 \
          -hostname-only-if-ssh \
          -jobs $(jobs -p | wc -l) \
          -modules 'time,venv,user,host,ssh,cwd,perms,git,hg,jobs,exit'
        )"

        # Uncomment the following line to automatically clear errors after showing
        # them once. This not only clears the error for powerline-go, but also for
        # everything else you run in that shell. Don't enable this if you're not
        # sure this is what you want.

        #set "?"
      }

      if type powerline-go > /dev/null 2>&1; then
        PROMPT_COMMAND="_update_ps1; $PROMPT_COMMAND"
      fi
