---

- name: Fetch hashicorp gpg key
  ansible.builtin.get_url:
    url: "https://apt.releases.hashicorp.com/gpg"
    dest: /tmp

- name: Dearmor hashicorp gpg key
  ansible.builtin.shell: "gpg --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg /tmp/gpg"
  args:
    creates: /usr/share/keyrings/hashicorp-archive-keyring.gpg

- name: Remove temporary hashicorp gpg key
  ansible.builtin.file:
    path: /tmp/gpg
    state: absent

- name: Add hashicorp repository
  ansible.builtin.apt_repository:
    repo: "deb [arch=amd64 signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com {{ ansible_distribution_release if ubuntu_release_override is not defined else ubuntu_release_override }} main"
    state: present
    filename: "hashicorp"
    update_cache: true

- name: Install vagrant
  ansible.builtin.package:
    name: vagrant
    state: present
