---

- name: Fetch spotify gpg key
  ansible.builtin.get_url:
    url: "https://download.spotify.com/debian/pubkey_C85668DF69375001.gpg"
    dest: /tmp

- name: Dearmor spotify gpg key
  ansible.builtin.shell: "gpg --dearmor -o /etc/apt/trusted.gpg.d/spotify.gpg /tmp/pubkey_C85668DF69375001.gpg"
  args:
    creates: /etc/apt/trusted.gpg.d/spotify.gpg

- name: Remove temporary spotify gpg key
  ansible.builtin.file:
    path: /tmp/pubkey_C85668DF69375001.gpg
    state: absent

- name: Add spotify repository
  ansible.builtin.apt_repository:
    repo: "deb [arch=amd64 signed-by=/etc/apt/trusted.gpg.d/spotify.gpg] http://repository.spotify.com stable non-free"
    state: present
    filename: "spotify"
    update_cache: true

- name: Install spotify client
  ansible.builtin.package:
    name: spotify-client
    state: present
