---

- name: Fetch microsoft gpg key
  ansible.builtin.get_url:
    url: "https://packages.microsoft.com/keys/microsoft.asc"
    dest: /tmp

- name: Dearmor microsoft gpg key
  ansible.builtin.shell: "gpg --dearmor -o /usr/share/keyrings/microsoft.gpg /tmp/microsoft.asc"
  args:
    creates: /usr/share/keyrings/microsoft.gpg

- name: Remove temporary microsoft gpg key
  ansible.builtin.file:
    path: /tmp/microsoft.asc
    state: absent

- name: Add microsoft repository
  ansible.builtin.apt_repository:
    repo: "deb [arch=amd64 signed-by=/usr/share/keyrings/microsoft.gpg] https://packages.microsoft.com/repos/edge stable main"
    state: present
    filename: "microsoft"
    update_cache: true

- name: Install Edge
  ansible.builtin.package:
    name: microsoft-edge-stable
    state: present
