---

- hosts: desktop-dev
  remote_user: '{{ provision_user }}'
  become: '{{ provision_become }}'
  roles:

    - apt-upgrade
    - basic-utils
    - powerline-go
    - blesh
    - atuin
    - geerlingguy.docker
    - ddev
    - geerlingguy.php-versions
    - geerlingguy.php
    - virtualbox
    - vagrant
    - vagrant-hostmanager-sudoers
    - 1password
    - microsoft-edge
    - spotify
    - snaps
    - git-configs
    - tailscale
