---

- hosts: all
  remote_user: '{{ provision_user }}'
  become: '{{ provision_become }}'
  roles:

    - apt-upgrade
    - basic-utils
    - ctorgalson.nerdfonts
    - fish
    - konsole-profile
    - geerlingguy.docker
    - ddev
    # enable the following line if the desired version of PHP is not shipped with the OS
    # - geerlingguy.php-versions
    - geerlingguy.php
    - virtualbox
    - vagrant
    - vagrant-hostmanager-sudoers
    - firefox
    - 1password
    - microsoft-edge
    - snaps
    - git-configs
    - tailscale
