---

- name: ctorgalson.nerdfonts
  src: https://github.com/ctorgalson/ansible-role-nerdfonts.git
  version: 'v1.0.1'

- name: geerlingguy.docker
  src: https://github.com/geerlingguy/ansible-role-docker.git
  version: '8.0.0'

- name: geerlingguy.php-versions
  src: https://github.com/geerlingguy/ansible-role-php-versions.git
  version: '7.0.1'

- name: geerlingguy.php
  src: https://github.com/geerlingguy/ansible-role-php.git
  version: '6.0.0'
